### ISSUE TITLE
WebDriver Issue

### ISSUE THREAD

**Issue by edwardhu** [timgrossmann/instagram-profilecrawl#1]
Excuse me, I've changed the webdriver to newest version by chrome.
But still happened the same error.. how to fix it?

Traceback (most recent call last):
  File "/Users/edward/instagram-profilecrawl/crawl_profile.py", line 11, in <module>
    browser = webdriver.Chrome('./assets/chromedriver')
  File "/Library/Python/2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by timgrossmann** [comment]
@edwardhu do you have the right version for your system?

**Comment by ToJen** [comment]
I think I know what's wrong, I had the same issue. `chromedriver` has to be in the same directory as `crawl_profile.py`. I got the [latest version](https://sites.google.com/a/chromium.org/chromedriver/downloads) of chromedriver and pasted it in the root of the git repository and ran it from there.

@timgrossmann can I make a pull request for this?

**Comment by ToJen** [comment]
Actually, the version in` assets/` might be the problem. I just put the updated version in that folder and it's working. Maybe we need to find a way to automatically download the latest version into `assets/`.

**Comment by edwardhu** [comment]
@timgrossmann I'm using 3.6 from official website. And with early 2.7 build in mac by default but I'm still using 3.6

**Comment by ToJen** [comment]
I don't think your version of python is the issue, for me it was just updating `chromedriver`.

**Comment by edwardhu** [comment]
@ToJen I updated the path in crawl_profile and it works! Thank you very much!
