### ISSUE TITLE
Class name error when crawling posts

### ISSUE THREAD

**Issue by dshahrokhian** [timgrossmann/instagram-profilecrawl#100]
(This issue is related to #78)

Most of the times, when one tries to crawl the post information from an user, the logging provides the following output:

`Message: no such element: Unable to locate element: {"method":"class name","selector":"Xl2Pu"`

If it helps, I am using MacOS with chromedriver.

Thanks for your time
Daniyal

**Comment by justdvl** [comment]
Well, as a matter of fact, it seems like the whole thing doesn't really work anymore. Maybe Instagram did an update. I'm having a look at it now.
