### ISSUE TITLE
How do you start USING it?

### ISSUE THREAD

**Issue by sonnyobrien** [timgrossmann/instagram-profilecrawl#102]
python3.5 crawl_profile.py 'user'
brings back nothing in cmd under windows 64 bit
I tried typing py -3.5 crawl_profile.py 'user'... nothing

Only resulting message i got was this:
```
C:\Users\SONNY64BIT\instagram-profilecrawl>py -3.5 crawl_profile.py sonnyobrien
Traceback (most recent call last):
  File "crawl_profile.py", line 7, in <module>
    from util.datasaver import Datasaver
  File "C:\Users\SONNY64BIT\instagram-profilecrawl\util\datasaver.py", line 5, i
n <module>
    from .util import check_folder
  File "C:\Users\SONNY64BIT\instagram-profilecrawl\util\util.py", line 1, in <mo
dule>
    from selenium.common.exceptions import NoSuchElementException
ImportError: No module named 'selenium'

C:\Users\SONNY64BIT\instagram-profilecrawl>
```

Also, where on earth do I input the username of the profile I want to crawl?

**Comment by sonnyobrien** [comment]
Sorry, this does not solve it. I already have selenium via pip install.

**Comment by rodrigoberriel** [comment]
@sonnyobrien You can always run pip like this: `python3.5 -m pip install selenium`

**Comment by rodrigoberriel** [comment]
@sonnyobrien As I said, in your case, a Windows user: `py -3.5 -m pip install selenium`.

**Comment by sonnyobrien** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

>py -3.5 -m pip install selenium
Requirement already satisfied: selenium in c:\python35\lib\site-packages (3.141.
0)
Requirement already satisfied: urllib3 in c:\python35\lib\site-packages (from se
lenium) (1.24.1)

like I said, selenium is already installed

**Comment by sonnyobrien** [comment]
You're right. I can not run an import selenium...
maybe I need to format my computer? I will close this as it does not relate to the repository.
