### ISSUE TITLE
Likes are not retrieved unless logged in

### ISSUE THREAD

**Issue by justdvl** [timgrossmann/instagram-profilecrawl#108]
Instagram made a changes not allowing to see who liked the photo unless we are logged in.
I propose quick fix for those who need to solve this:

To solve it, one simple solution is to just add a cookie to the browser, thus getting logged in automatically.
You can get your instagram cookie if you use InstaPy, it is saved in logs file.
Let's say we name cookie: "_insta_cookie.pkl_" and we put it into _logs_ folder.

Than to crawl_profile.py file, we add at the beginning: 

```
import time
import pickle
```

and just after browser declaration (cca line 25) we add:

```
try:
    browser.get("http:www.google.com")
    time.sleep(1)
    for cookie in pickle.load(open('logs/insta_cookie.pkl', 'rb')):
                browser.add_cookie(cookie)
    time.sleep(1)            
except:
    print ("adding cookie failed")
```

It is up to discussion is we want to include logging in feature into this project as well.

**Comment by imansh77** [comment]
Nice job, but I think it's not a good practice to use cookies to log in because maybe someone didn't log in with his/her browser (which mostly true because people use mobile for instagram usage) and it'll fail so in my opinion its a better approach to log in completely (at least for first time and then save it for next use)

**Comment by timmoh** [comment]
Hey @imansh77 I cannot merge this request, this would break every installation of instagram profilecrawl. you changed the complete behavior from calling the script with serval usernames to a script with just one username and credentials.
Please rewrite your code so the user login is optional.
perhaps by putting the user/pw settings into the script like Instapy does it....
