### ISSUE TITLE
Scrapping break errors

### ISSUE THREAD

**Issue by davidetroise** [timgrossmann/instagram-profilecrawl#112]
Dear David,
Thanks to your intervention now the script don't stop anymore at 42 posts, but I’m still having the other problems:

I don’t get the comments' text and neither the correct number of comments of a single post:

> click button for loading more
> error on clicking - next try (tried: 0)comments:26)
> click button for loading more
> error on clicking - next try (tried: 1)comments:26)

> INFO [2018-11-13 11:25:17] found comments2
> ERROR [2018-11-13 11:25:27] ERROR something went wrong getting user_commented
> ERROR [2018-11-13 11:25:27] ERROR something went wrong getting comment
> ERROR [2018-11-13 11:25:38] ERROR something went wrong getting user_commented
> ERROR [2018-11-13 11:25:38] ERROR something went wrong getting comment
> INFO [2018-11-13 11:25:38] 0 comments.

I tried with two the different accounts, a bigger one https://www.instagram.com/scottecss/, and also https://www.instagram.com/fibrax/ since it has very few post and comments.

I’m attaching to you the JSON file, the commenters list, and the terminal log of the _scottecss_ account.

[scottecss.zip](https://github.com/timgrossmann/instagram-profilecrawl/files/2609348/scottecss.zip)

Thanks for your help,
D.

_Originally posted by @davidetroise in https://github.com/timgrossmann/instagram-profilecrawl/issues/103#issuecomment-441128806_

**Comment by justdvl** [comment]
I see some errors, such as _Unable to locate element: {"method":"tag name","selector":"span"}_

Yea there are some problems in this code, such as user_commented is _tried_ to be declared, and then, no matter if try statement succeeds or not, it is used in another code. 
So if that try statement fails and brings exception, user_commented is still called and that cause error.

I'm busy now I'll look into it more tomorrow.

**Comment by davidetroise** [comment]
I kept on making some tests but I'm still having the same results, the script still gives me the same errors. Have you had a chance to look into this? 

Thanks, D.

**Comment by noiob** [comment]
I fixed this in #133, the problem is that the button is sometimes obscured by a popover (probably the GDPR cookie notice).
