### ISSUE TITLE
video views and likes

### ISSUE THREAD

**Issue by msabic22** [timgrossmann/instagram-profilecrawl#114]
I noticed that video views count as likes, so i tried to fix this by changing extractor_post util (extract_post_info funciton)
i replaced this :

 ` likes = 0

    if len(post.find_elements_by_tag_name('section')) > 2:
        likes = post.find_elements_by_tag_name('section')[1] \
            .find_element_by_tag_name('div').text
        likes = likes.split(' ')

        # count the names if there is no number displayed
        if len(likes) > 2:
            likes = len([word for word in likes if word not in ['and', 'like', 'this']])
        else:
            likes = likes[0]
            likes = likes.replace(',', '').replace('.', '')
            likes = likes.replace('k', '00')
        InstaLogger.logger().info("post-likes:" + likes)`

with this :
`    likes = 0
    views = 0

    likes = browser.find_element_by_xpath("//section[contains(@class,'EDfFK ygqzn')]/div").text

    if "views" in likes:
        likes = likes.split()
        views = likes[0]
        views_element = browser.find_element_by_xpath("//div[contains(@class,'HbPOm _9Ytll')]/span")
        browser.execute_script("arguments[0].click();", views_element)
        likes = browser.find_element_by_xpath("//div[contains(@class,'vJRqr')]/span").text

        likes = likes.replace(',', '').replace('.', '')
        likes = likes.replace('k', '00')

        views = views.replace(',', '').replace('.', '')
        views = views.replace('k', '00')

        InstaLogger.logger().info("post-likes:" + likes)
        InstaLogger.logger().info("post-views:" + views)

    else:
        likes = likes.split(' ')

        # count the names if there is no number displayed
        if len(likes) > 2:
            likes = len([word for word in likes if word not in ['and', 'like', 'this']])
        else:
            likes = likes[0]
            likes = likes.replace(',', '').replace('.', '')
            likes = likes.replace('k', '00')
        InstaLogger.logger().info("post-likes:" + likes)
`

its mabye badly written but it works.. 
also i added views argument and return to extract_post_info function
and added views to log_stats

**Comment by noiob** [comment]
I fixed this in #133 fyi, it scrapes views and likes separately
