### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by shapetheLOLa** [timgrossmann/instagram-profilecrawl#12]
instapy is running perfectly, however I'm having trouble starting profilecrawl. Heres the output after trying to start it :

`Traceback (most recent call last):
  File "crawl_profile.py", line 18, in <module>
    browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/home/jwkoch/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/jwkoch/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/jwkoch/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/jwkoch/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/home/jwkoch/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-83-generic x86_64)
`

You got any hints/ideas?

**Comment by timgrossmann** [comment]
@shapetheLOLa Hmm... this is really weird. Sounds like it's either the wrong chrome driver for your system or your droplet hasn't got enough power (RAM)

**Comment by shapetheLOLa** [comment]
Im using the same chromedriver as in instapy, I've just copied it to the other location.

**Comment by tcvieira** [comment]
@shapetheLOLa 
On the log looks like it´s using selenium webdriver from python2.7
`"/home/jwkoch/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py"`
Try install selenium for python3
`pip3 install selenium`
and run with python3

**Comment by shapetheLOLa** [comment]
Oh sorry, yea but same error there. I've just tried it with python 2.7 after 3 didnt work.
I've also tried using a later chromedriver version.

Here is the output 
`⇒  python3.5 crawl_profile.py
Traceback (most recent call last):
  File "crawl_profile.py", line 18, in <module>
    browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/home/jwkoch/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/jwkoch/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/jwkoch/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/jwkoch/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/home/jwkoch/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 4.4.0-83-generic x86_64)`

**Comment by tcvieira** [comment]
@shapetheLOLa 
Have you tried this [stackoverflow question](https://stackoverflow.com/questions/35212993/selenium-fails-to-start-chromedriver) ?
Are you running as root?

**Comment by shapetheLOLa** [comment]
This won't help, will it? the chromedriver is in the assets folder, not /opt/google or /opt/.

I've tried putting it there and put a link to the assets folder, still no luck

**Comment by Jayphen** [comment]
I had this problem. You need to make sure it's running as headless.

In `crawl_profile.py`, add 
`chrome_options.add_argument('--headless')`

below the other similar add_argument lines

**Comment by staringispolite** [comment]
Strange, I'm getting this too, though in InstaPy. I have two digital ocean droplets running from the same Snapshot. One (the original) works fine. The other (created from a Snapshot) gets this error. Systems/paths/etc should be the same. 

Perhaps that's a clue? Tried all the workarounds above to no avail

**Comment by williamsandytoes** [comment]
I also had this problem, even though I was staring chrome in headless mode. For those who come across this in the future, I found adding "--no-sandbox" to the chrome startup arguments solved the problem.
E.g. `chrome_options.add_argument('--no-sandbox')`

**Comment by k1ltr0** [comment]
for some reason, wasnt working with chromedriver 2.29, had to update to 2.35 and worked

**Comment by djlowes** [comment]
Following on from @k1ltr0 - I have just had to update to v2.36 from 2.33 after receiving this error message. It's working fine now.

**Comment by r8w9a5k** [comment]
Hello,
I got 2 identical Dell computers with both win10.
First one can run selenium via simple python code

```
from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://www.google.cz')
```

Second pc cannot run it. I tried to do everything I read on the internet but still getting error:

`selenium.common.exceptions.WebDriverException: Message: unknown error: chrome failed to start`
`(Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.16299 x86_64)`

I tried to add _chrome_options.add_argument('--headless')_ and _chrome_options.add_argument('--no-sandbox')_ + I set Path variable and still getting this error.

Do you know how to solve it?

**Comment by happyhq** [comment]
@r8w9a5k  which your version of python?

**Comment by happyhq** [comment]
@r8w9a5k 
I meet the same problem。before，I  think it‘s the version of python。But NOT。
it ’s the veriosn of  chrome。
Please choice the  right version of  chrome  and chromedriver。
You can see from https://sites.google.com/a/chromium.org/chromedriver/。

**Comment by r8w9a5k** [comment]
@happyhq I am using python 3.6.1 and latest chromedriver 2.3.7

**Comment by r8w9a5k** [comment]
@happyhq Today I tried to run that on python 3.6.5 and chromedriver 2.3.7 with both 32bit or 64 bit and it still doesn't work. I am really angry why two indetical Dell computers differs.

**Comment by happyhq** [comment]
@r8w9a5k   Maybe the version of chrome is  too old.

**Comment by r8w9a5k** [comment]
@happyhq Version of Chrome browser is the latest. Chromedriver is also up to date. I tried lower versions but error is still same.

**Comment by r8w9a5k** [comment]
@happyhq I solved my problem. I used procmon to trace what's going on with chromedriver.exe and I found out that the problem was in admin rights. I simply checked to run my IDLE and chromedriver as administrator  and now it works just fine.

**Comment by timmoh** [comment]
@timgrossmann can be closed
