### ISSUE TITLE
Login trouble

### ISSUE THREAD

**Issue by imansh77** [timgrossmann/instagram-profilecrawl#120]
Hey there, apparently after trying to log in, Instagram sends a code via SMS so here we have trouble any ideas how to handle it? my guess: maybe freeze the app, get the code from the user via CLI and put it for Instagram then continue the rest of process. @timmoh @timgrossmann

**Comment by justdvl** [comment]
Yes. I already wrote that code. I'll push it soon.
We will also need login to make more unsuspicious, so Instagram won't even
need to ask (like in case of Instapy).

**Comment by imansh77** [comment]
@justdvl nice job, so how did you handle it?
