### ISSUE TITLE
useless creation of crawl_profile_with_login.py

### ISSUE THREAD

**Issue by imansh77** [timgrossmann/instagram-profilecrawl#122]
@timmoh are you sure it is a good approach to have two way? because we have login_username in settings.py and again in this file we have settings.login_username and even in original crawl_porfile.py I think it makes user confuse and harder to maintain that's enough having one it does the job.

_Originally posted by @imansh77 in https://github.com/timgrossmann/instagram-profilecrawl/commit_comment/create#commitcomment-31796469_

**Comment by timmoh** [comment]
what's the problem?
by default python would use the login_username in settings.py ... if you want to overwrite it for a single script you could overwrite (like every setting) with settings.login_username

**Comment by imansh77** [comment]
@timmoh yeah but I mean why do we need a new file when settings.py do the thing

**Comment by timmoh** [comment]
I don't see any new file.... crawl_profile_with_login.py is just an example file

**Comment by imansh77** [comment]
don't you think it'll make confusion?

**Comment by timmoh** [comment]
@imansh77 perhaps we should set up an folder "examples" and move this file to there
