### ISSUE TITLE
Issue on crawl with login

### ISSUE THREAD

**Issue by gharary** [timgrossmann/instagram-profilecrawl#123]
I have an issue when I want to use my username&password to crawl a private profile which I have followed.
I get this error:

Message:                                                                          username or password is wrong
--

however I've changed my password and tried again didn't work. I've disabled my two-factor authentication and still doesn't work!

Any idea about it?

**Comment by imansh77** [comment]
@gharary I guess you are trying to run  "crawl_profile_with_login.py" am I right? If yes its because 
Settings.login_username = 'my_insta_account'
Settings.login_password = 'my_passwort_xxx'
 maybe you didn't change this one and you changed below which is in "settings.py" :
    login_username = ''
    login_password = ''
@timmoh that's what I'm talking about in that issue which I opened it makes confusion even for us which developed some parts! my suggestion is to delete "crawl_profile_with_login.py" and make the user enter login username & password in settings.py and only run "crawl_profile.py" hope I made my point.

**Comment by Cupido10** [comment]
@imansh77  Sorry, I have tried your way to do so, but still pop up error message. 
Are there any solution?  thanks!

**Comment by imansh77** [comment]
@Cupido10 can you say what exactly did you do? and as @timmoh said make sure you have updated your repo and try once again.

**Comment by Cupido10** [comment]
@timmoh Yes, I've already update to the lateset version.
@imansh77 I follow some previous issue and run crawl_profile.py with login username & password in setting.py. But It appears " error password " and do nothing. :(

**Comment by dkbast** [comment]
Hi, I believe the problem is coming from Instagrams "we detected an unusual login attempt" . InstaPy has taken care of this problem: "bypass_suspicious_attempt=True" - maybe the code can be reused?

**Comment by lordlynx** [comment]
I have the same problem too;Messege: username or password is wrong Error with user xxxxxxxxx


> @gharary I guess you are trying to run "crawl_profile_with_login.py" am I right? If yes its because
> Settings.login_username = 'my_insta_account'
> Settings.login_password = 'my_passwort_xxx'
> maybe you didn't change this one and you changed below which is in "settings.py" :
> login_username = ''
> login_password = ''
> @timmoh that's what I'm talking about in that issue which I opened it makes confusion even for us which developed some parts! my suggestion is to delete "crawl_profile_with_login.py" and make the user enter login username & password in settings.py and only run "crawl_profile.py" hope I made my point.

also tried imansh77's suggestion but didn't work

**Comment by 0rC0** [comment]
Same error here, and at least in my case @dkbast is right, there is no distinction between failed login because of a wrong user/pass or because it asks for a security code (file `instagram_profilecrawl/util/account.py`).
