### ISSUE TITLE
Error in Readme?

### ISSUE THREAD

**Issue by HarryRowolt** [timgrossmann/instagram-profilecrawl#125]
Readme says: 
**Settings:**
To limit the amount of posts to be analyzed, change variable limit_amount in crawl_profile.py. Default value is 12000.\

There is no "limit_amount" in crawl_profile.py - you refer to settings.py?

**Comment by timgrossmann** [comment]
@HarryRowolt Sorry, yes, absolutely!
Could you create a PR to adjust the description in the README, please?

**Comment by timmoh** [comment]
changed it
