### ISSUE TITLE
Cannot get the list of likers

### ISSUE THREAD

**Issue by perryd01** [timgrossmann/instagram-profilecrawl#131]
`ERROR [2019-01-28 17:20:03] Error - getting post likers`
`ERROR [2019-01-28 17:20:03] can only concatenate str (not "NoSuchElementException") to str `
......
`INFO [2019-01-28 17:20:01] GETTING LIKERS FROM POST`
`INFO [2019-01-28 17:20:01] found likers: 0 should be 56 -- scroll for more`
`ERROR [2019-01-28 17:20:01] Error - getting post likers`
`ERROR [2019-01-28 17:20:01] can only concatenate str (not "NoSuchElementException") to str`

so hey, i cant get the list of the likers
tried tweaking the settings file, tried w the templates, set the timout to 60sec, but still cant.

**Comment by miladyalda** [comment]
> `ERROR [2019-01-28 17:20:03] Error - getting post likers`
> `ERROR [2019-01-28 17:20:03] can only concatenate str (not "NoSuchElementException") to str `
> ......
> `INFO [2019-01-28 17:20:01] GETTING LIKERS FROM POST`
> `INFO [2019-01-28 17:20:01] found likers: 0 should be 56 -- scroll for more`
> `ERROR [2019-01-28 17:20:01] Error - getting post likers`
> `ERROR [2019-01-28 17:20:01] can only concatenate str (not "NoSuchElementException") to str`
> 
> so hey, i cant get the list of the likers
> tried tweaking the settings file, tried w the templates, set the timout to 60sec, but still cant.

Hello! I have same problem.

**Comment by doganaltintas** [comment]
Hello! I have same problem. Post likes constant count turn zero.

**Comment by audacesk** [comment]
Hi guys @doganaltintas  @miladyalda @perryd01 , I was wondering if you found the solution to your problem?  I have the same issue. I've been playing around the entire day but I must be missing something somewhere
Thanks guys

**Comment by timmoh** [comment]
Instagram has a new feature it hides the likers which are not in actual view. so is hard for us to get the whole likerslist....
perhaps some can build a work around like adding the found likers to an array, scroll, adding to an array (the array must be checked if there no duplicate entry)
