### ISSUE TITLE
Is there a way to update whats previously been scraped?

### ISSUE THREAD

**Issue by snrkldetection** [timgrossmann/instagram-profilecrawl#135]
First of all so impressed with what you have done here.

Is there a way that i am missing that would just scrape the data of the non scraped (new) posts and amend it to the downloaded JSON?

This would be amazing, currently its just looping and redownloading my profile (about an hour at a time ) when i relaunch the command

**Comment by timmoh** [comment]
if you want to crawl some other profiles you have to call the script with other users crawl_profile.py user1 user2
