### ISSUE TITLE
Ways of Increment the velocity of the crawling?

### ISSUE THREAD

**Issue by iBocchese** [timgrossmann/instagram-profilecrawl#142]
Has anyone tried to implement some modifications to the repository to crawl faster?

For example, I crawled Rihanna' s profile, but it took days, precisely 5. 
Also, when it requires too much time download info, the crawl generates automatically an error of download and starts downloading the next element...

**Comment by timmoh** [comment]
it depends on your use case, everything could be configured:
Don't crawl posts or just X posts
Don't crawl like
Don't crawl follower
Don't crawl comments

**Comment by prafulfillment** [comment]
I added a new [function](https://github.com/timgrossmann/instagram-profilecrawl/blob/master/util/extractor.py#L336) that's used by default that captures number of likes, number of views, number of comments, caption, location, and a [few other pieces of data](https://github.com/timgrossmann/instagram-profilecrawl/blob/master/util/extractor.py#L369-L403) which makes crawling significantly faster.

It doesn't capture comments, likers, commenters, and other pieces of data you'd need by visiting each post & scrolling through the DOM.
