### ISSUE TITLE
Also crawl following list

### ISSUE THREAD

**Issue by LupascuAndrei** [timgrossmann/instagram-profilecrawl#143]
https://github.com/timgrossmann/instagram-profilecrawl/blob/ae56d85175a4ceb867ce2d310c427583046e7ca2/util/extractor.py#L132

I see we're able to crawl the followers list, which works flawless.
Will extracting the following list also be possible in the near future? Has it been tried recently ( are there some issues which made it impossible/hard to implement? ) ?

**Comment by timmoh** [comment]
it already implemented. Use Settings.scrape_follower = True (login credentials are needed)

just updated documentation
