### ISSUE TITLE
scrape followers list with error

### ISSUE THREAD

**Issue by nightmello** [timgrossmann/instagram-profilecrawl#146]
Thanks for this repo.

When I test the 03/05/2019 version, it can return the first 9 followers instead of 12 (current hard-code value). How to return the entire followers list?

The running error is from [here](https://github.com/timgrossmann/instagram-profilecrawl/blob/master/util/extractor.py#L153-L159). 
`Unexpected error: <class 'IndexError'>`
`list index out of range`
`ERROR [2019-03-28 23:07:07] Cannot get Follower List`

Also, [second part](https://github.com/timgrossmann/instagram-profilecrawl/blob/master/util/extractor.py#L172-L173) always return 0.

Anyone knows how to fix it?

**Comment by itsdante** [comment]
@nightmello have you logged in ? extracting follower data requires you to login

**Comment by nightmello** [comment]
> @nightmello have you logged in ? extracting follower data requires you to login

Yes, I logged in. Finally, I switch to use Instapy: https://github.com/nightmello/instagram-profilecrawl/blob/master/crawl_real_fans.py
