### ISSUE TITLE
Chromedriver is not in path error on Windows 10

### ISSUE THREAD

**Issue by Suleman-Elahi** [timgrossmann/instagram-profilecrawl#148]
Even though, Chromedriver is in PATH, it still showing error message.

![image](https://user-images.githubusercontent.com/24384996/58368524-278f9100-7ea3-11e9-8203-52e5932dcceb.png)

**Comment by TollyThaWally** [comment]
If you've downloaded chromedriver.exe, put it in the assets folder. (It worked for me)

**Comment by Suleman-Elahi** [comment]
Thanks.
