### ISSUE TITLE
get location latitude and longitude not working

### ISSUE THREAD

**Issue by sejaldua** [timgrossmann/instagram-profilecrawl#156]
something goes wrong in between 

```python
url = 'https://www.instagram.com/explore/locations/' + str(location_id) + '/?__a=1'
response = requests.get(url)
```

and 

```python
data = response.json()
lat = data['graphql']['location']['lat']
lng = data['graphql']['location']['lng']
```

tried to debug this with print statements and i'm getting a JSONDecodeError when trying to call `response.json()`

does anyone know what is going on here?

**Comment by timmoh** [comment]
Instagram has delete this value in graphql in some locations.
