### ISSUE TITLE
I can't get post's comments 

### ISSUE THREAD

**Issue by karenbarreto** [timgrossmann/instagram-profilecrawl#162]
I'm trying to get the post info and comments. 

<img width="1377" alt="Screen Shot 2019-11-15 at 12 55 02" src="https://user-images.githubusercontent.com/56891248/68956603-33e80d00-07a7-11ea-9b8d-6f67afede32c.png">

<img width="806" alt="Screen Shot 2019-11-15 at 12 56 08" src="https://user-images.githubusercontent.com/56891248/68956682-5b3eda00-07a7-11ea-867a-9e23a7f4ec62.png">

<img width="803" alt="Screen Shot 2019-11-15 at 12 56 19" src="https://user-images.githubusercontent.com/56891248/68956697-609c2480-07a7-11ea-940f-6df2c658e449.png">

**Comment by karenbarreto** [comment]
How can I get all comments from post?

**Comment by jat28468** [comment]
please make a video how to launch in termux

**Comment by timmoh** [comment]
Did you set the settings? @karenbarreto 
`Settings.scrape_posts_infos = True
Settings.output_comments = True`

**Comment by rolaxbell** [comment]
same issue, and i've set both of these to true:

```
Settings.scrape_posts_infos = True
Settings.output_comments = True
```

--maybe related, but tags aren't being separated from the profile post's description.
--maybe related, i only see "count" for followers and following, is there supposed to be an additional key with the actual names/ids of the followers?

let me know if i should start a new issue for those! 

thanks again in advance!!
