### ISSUE TITLE
Error in line 19

### ISSUE THREAD

**Issue by djrbeen** [timgrossmann/instagram-profilecrawl#171]
Hi Tim,
First fo all thank you for sharing your excellent work!
Now, I have this issue when I run the script
`DevTools listening on ws://127.0.0.1:55337/devtools/browser/f1d37825-f242-4970-8c71-8783f5f5d832
Extracting information from xxxxxxx
INFO [2020-03-26 11:01:38] Extracting information from xxxxxxx
INFO [2020-03-26 11:01:41] Alias name: xxxxxxx
INFO [2020-03-26 11:01:41] Bio:
INFO [2020-03-26 11:01:41] Url:
INFO [2020-03-26 11:01:41] Posts: {'count': 159}
INFO [2020-03-26 11:01:41] Follower: 320
INFO [2020-03-26 11:01:41] Following: {'count': 354}
INFO [2020-03-26 11:01:41] Is private: False
0
Traceback (most recent call last):
  File "crawl_profile.py", line 19, in <module>
    information, user_commented_list = extract_information(browser, username, Settings.limit_amount)
  File "C:\xxx\xxx\xxx\xxx\xxx\xxx\instagram-profilecrawl\util\extractor.py", line 459, in extract_information
    post_infos, user_commented_total_list = quick_post_extract(browser, num_of_posts_to_do)
  File "C:\xxx\xxx\xxx\xxx\xxx\xxx\instagram-profilecrawl\util\extractor.py", line 390, in
quick_post_extract
    'caption': post_json['caption'],
KeyError: 'caption'`

How can I fix it?

**Comment by vmdhhh** [comment]
Refer to this solution.
https://github.com/timgrossmann/instagram-profilecrawl/issues/172#issuecomment-612528595
