### ISSUE TITLE
Getting error in extractor.py

### ISSUE THREAD

**Issue by suryansh2020** [timgrossmann/instagram-profilecrawl#172]
![image](https://user-images.githubusercontent.com/22264793/77838867-b7f7cb80-716f-11ea-9b61-9e260abf4864.png)

**Comment by Skrohk** [comment]
Go in the file extractor.py, line 390 and replace the line by : 'caption': post_json.get('caption'),

I have got the same issue and now it works !

**Comment by Skrohk** [comment]
The problem occurs when the caption of an image is blank. 

Just replace in extractor.py the line 390 by "'caption': post_json.get('caption')," and it will works ;)

**Comment by nisrinaps** [comment]
![ERROR](https://user-images.githubusercontent.com/44310392/85500783-5f20bd80-b60e-11ea-92e6-431e063b881a.PNG)
Please help, I got the similar error. I even don't know what need to be change in the line 410. Anyone knows?
Thx
