### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException

### ISSUE THREAD

**Issue by vmdhhh** [timgrossmann/instagram-profilecrawl#175]
I am getting following error after sometime

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".v9tJq"}
  (Session info: headless chrome=81.0.4044.138)

Please let me know if there is any solution around this.

P.S Great crawler overall.

**Comment by ineedhacker12345** [comment]
Same here

**Comment by vmdhhh** [comment]
@timmoh @timgrossmann 
Is there any way we can include rotating proxy in this crawler?
I'm facing this issue after continuous profile crawl.
Please help.

**Comment by timmoh** [comment]
> @timmoh @timgrossmann
> Is there any way we can include rotating proxy in this crawler?
> I'm facing this issue after continuous profile crawl.
> Please help.

https://github.com/timgrossmann/instagram-profilecrawl/issues/134

**Comment by vmdhhh** [comment]
I got that i will have to reinitialize the browser after sometime with new proxy.
I'm just confused how can i do it in the code.
@timmoh any help is really appreciated. Thanks

**Comment by timmoh** [comment]
sry no support for this feel free to implement it on your own. all code is given, you just need to add an loop
