### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by arip-1990** [timgrossmann/instagram-profilecrawl#177]
![image](https://user-images.githubusercontent.com/21642196/82218264-4e509e00-9924-11ea-83c7-829dc686a2de.png)

**Comment by arip-1990** [comment]
I commented out the line 'chrome_options.add_argument (' - headless ')' and looked in the browser. authorization is successful

**Comment by arip-1990** [comment]
and how to get information about comments and likes for the post. those. how to get usernames like or comment

**Comment by arip-1990** [comment]
there is no such class on the instagram site 'WebDriverWait (browser, 10) .until (EC.presence_of_element_located ((By.CLASS_NAME, "XrOey")))'.
account.py file line 62

**Comment by arip-1990** [comment]
after fixing the error a new error appeared:
FileNotFoundError: [Errno 2] No such file or directory:' ./cookies/cookies-arip_1990.pkl '

**Comment by arip-1990** [comment]
new error 'Object of type InstagramUser is not JSON serializable'

**Comment by bejarano-tech** [comment]
> new error 'Object of type InstagramUser is not JSON serializable'

Hi, i change:
from:
`        Datasaver.save_profile_json(username,information)`
to:
`        Datasaver.save_profile_json(username, information.to_dict())`

in the file: crawl_profile_with_login.py

and it Works

**Comment by rsa408** [comment]
> there is no such class on the instagram site 'WebDriverWait (browser, 10) .until (EC.presence_of_element_located ((By.CLASS_NAME, "XrOey")))'.
> account.py file line 62

how did you solved errors after this line?

**Comment by arip-1990** [comment]
> > there is no such class on the instagram site 'WebDriverWait (browser, 10) .until (EC.presence_of_element_located ((By.CLASS_NAME, "XrOey")))'.
> > account.py file line 62
> 
> how did you solved errors after this line?

I don't remember
