### ISSUE TITLE
TypeError: get_logger() missing 1 required positional argument: 'show_logs'

### ISSUE THREAD

**Issue by Lxhnnn** [timgrossmann/instagram-profilecrawl#178]

**Comment by abhitiiita** [comment]
.logger() is a class method but rest are instance method. I am also facing the same issue.

**Comment by meumesmo** [comment]
Getting the same error here.

**Comment by silvioraof** [comment]
me too

**Comment by rishabh-gupta-fk** [comment]
pass self as an argument.

**Comment by pranjal-b** [comment]
same issue

**Comment by gavishpoddar** [comment]
Same error

**Comment by TheAnachronism** [comment]
Also facing the same issue.

**Comment by testdriver123** [comment]
Same issue, please help.

**Comment by rishabh-gupta-fk** [comment]
Go to that logger class, and in all methods add an argument "self". That will resolve this.

**Comment by arihant-jain-09** [comment]
Where please help

**Comment by arihant-jain-09** [comment]
@rishabh-gupta-fk Bro where to add self its already there

**Comment by rishabh-gupta-fk** [comment]
@arihant-jain-09 Have a look at this. You can also look at my cloned version of this repo. But WARNING: I have fully changed it to my requirements and might not be of use to you. And it's also messed up.
![image](https://user-images.githubusercontent.com/70313971/97257637-87c6f700-183c-11eb-806d-5f4c9126dfe8.png)

**Comment by timmoh** [comment]
We are open for pull requests

**Comment by rishabh-gupta-fk** [comment]
> We are open for pull requests

I didn't get time to clean up my code, will submit a request as soon as I am able to get it done. 
Thanks for this repo. Helped me a lot :)
