### ISSUE TITLE
[Feature Request] - adding a function to the script so that it records the progress on each profile 

### ISSUE THREAD

**Issue by AriaShishegaran** [timgrossmann/instagram-profilecrawl#18]
Adding a read/write function to the script so that it updates the profile.json after each page crawl, now it only records if the process has been completed successfully, which has happened for me very rarely, most of time the script crashes for a reason and therefore nothing is saved.

**Comment by timgrossmann** [comment]
@AriaShishegaran That is a really nice idea.

As said on the other issue, I'm currently not really actively developing this further.
I hope I can find some time in the future to work on this a bit more.

**Comment by timmoh** [comment]
@AriaShishegaran it should save the json file if there is an error...
Could you pls close issue
