### ISSUE TITLE
[Feature Request] any plans for headless crawling? PhantomJS or similar?

### ISSUE THREAD

**Issue by AriaShishegaran** [timgrossmann/instagram-profilecrawl#19]
do you have any plans for adding phantom js integration so that the script is actually usable on production in contrast to now needing a GUI to run?

**Comment by timgrossmann** [comment]
@AriaShishegaran Good question.

Well, at least for InstaPy itself, the plans are to use the newly introduced headless feature of chrome itself to make sure we won't rely on any GUI.
But this still might take a while to be implemented...

I'm really sorry. I currently have an insanely full schedule...

**Comment by StefanUPB** [comment]
Seems like this has been dealt with and chrome is running headless. :)
