### ISSUE TITLE
fixed issue - comments problem

### ISSUE THREAD

**Issue by RealMakAttak** [timgrossmann/instagram-profilecrawl#22]
Sorry not great with github but there was a problem where comments = 0 on line 61 of extractor.py and then later tried to find the len of it which caused:

```
 return img, tags, int(likes), int(len(comments) - 1)
TypeError: object of type 'int' has no len()
```

if you just change comments = 0 to comments = [] then works fine.

**Comment by timgrossmann** [comment]
@RealMakAttak Could you please create a PR for that? 
Would really appreciate that.

**Comment by timgrossmann** [comment]
@RealMakAttak Could you please create a PR for that? 
Would really appreciate that.

**Comment by RealMakAttak** [comment]
@timgrossmann I'm not great with Github but I will try and do that (will be my first time sorry)

**Comment by timgrossmann** [comment]
@RealMakAttak No problem, great opportunity to learn 😉
