### ISSUE TITLE
Can't work since yesterday

### ISSUE THREAD

**Issue by zhaobr340104** [timgrossmann/instagram-profilecrawl#24]
The script can't get information since yesterday. It seems that  Instagram has changed the tag&class name on the html page? 
Error message：
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"_de9bg"}

**Comment by timgrossmann** [comment]
@zhaobr340104 Looks like they changed every single class for the elements... 😑

**Comment by jianglonger** [comment]
i think you are so good ,i am pround of you my son

**Comment by Jayphen** [comment]
I believe I've fixed this - PR #25

**Comment by timgrossmann** [comment]
@jianglonger @zhaobr340104 Please try if #25 fixed this for you

**Comment by jianglonger** [comment]
OK thanks，i will try it latter

**Comment by zhaobr340104** [comment]
Thank you very much.

**Comment by michellexyq** [comment]
hi @timgrossmann

I was not able to get information either and the error messages shows that it may be due to the same reason: 

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"_mesn5"}

Thanks!

**Comment by timgrossmann** [comment]
@michellexyq I'm really sorry you're having issues...

However currently I simply don't have the time to work on this any further, I hope you can understand this.

What you can do is copy that selector you posted and then check the code where you can find it.
This will give you an indication which element should be searched for.
Then head over to instagram and the page that should be searched for, open the dev console and in the elements tab, search for the new element selector...

Once I'm back at my university, I will remodel this tool to work with the graphql endpoints to make sure that this won't happen again...
I'm very sorry
