### ISSUE TITLE
css is dynamically generated, not hard coded

### ISSUE THREAD

**Issue by byzhou** [timgrossmann/instagram-profilecrawl#27]
https://github.com/timgrossmann/instagram-profilecrawl/blob/e657d6c4b443641053c8da4812593fb3abb30596/util/extractor.py#L98

**Comment by timgrossmann** [comment]
@byzhou In InstaPy we now use the text as a better indicator which doesn't break that fast.
Unfortunately, I don't have a lot time right now, so this repo won't get a lot of attention. Feel free to submit a PR to improve it!

Thank you
