### ISSUE TITLE
Logging In?

### ISSUE THREAD

**Issue by mattalhonte** [timgrossmann/instagram-profilecrawl#28]
Sorry if this is spelled out in the documentation (or InstaPy), but I was wondering if there was a way to login during the session.  I'd like to get the likes of a friend's pics, but his profile's private - I could access it if I could figure a way to log in during the Headless session.  Thanks!

**Comment by timgrossmann** [comment]
@mattalhonte Well, for this issue, unfortunately, as of now, there is no such way.

It's a nice idea, if you're interested, feel free to contribute to this project.
Thank you
