### ISSUE TITLE
fork of project on nodeJS

### ISSUE THREAD

**Issue by nacimgoura** [timgrossmann/instagram-profilecrawl#3]
Hello, I realized a fork of your project but since I do not know the python, I did it in nodejs and I tried to make improvements. It is still under development, so there are still bugs.
You can see it here : https://github.com/nacimgoura/instagram-profilecrawl

**Comment by timgrossmann** [comment]
@nacimgoura  Hey there, awesome!
Love the NodeJS version 😉
