### ISSUE TITLE
Unable to located element.

### ISSUE THREAD

**Issue by andrewjburnett** [timgrossmann/instagram-profilecrawl#33]
Here's my error. The script ran fine a few times but is now unable to locate this element.

[selenium.webdriver.remote.remote_connection] DEBUG: Finished Request {'sessionId': '202cae480ffc0f2e7f76665155ad5760', 'status': 7, 'value': {'message': 'no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@class, "_1cr2e _epyes")]"}\n  (Session info: chrome=64.0.3282.140)\n  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.12.6 x86_64)'}}

**Comment by timmoh** [comment]
@andrewjburnett is bug still present? or can we close issue?
