### ISSUE TITLE
Cant crawl, it print "-Only few posts" always 

### ISSUE THREAD

**Issue by s1011448** [timgrossmann/instagram-profilecrawl#34]
User has more than 12 posts but after running the program, only print out -Only few posts

**Comment by icebergyy** [comment]
I am getting the same issue.  Any idea what could be causing the problem?  I will take a look at the code

**Comment by s1011448** [comment]
@timgrossmann Sorry for bothering you. I am trying to fix it myself but still suffer problems, it seems that there's no load_button this element in the web page and some class name has changed. I would appreciate it very much if you have time to take a look at this project and give me some advice. 

Thank you~

**Comment by deniskrafczyk** [comment]
same issue for me :/

**Comment by AmirHadifar** [comment]
same issue here :(

**Comment by justdvl** [comment]
Hey guys, I fixed the bug, I'll try to contribute to it now (it is my first time working with GitHub so let me figure out how to do that).
The prev_divs needs to be changed to: prev_divs = browser.find_elements_by_tag_name('main')
Also the loading of page needs to be changed.
Then it works.

**Comment by justdvl** [comment]
What took me 2 hours to figure out is, that Instagram always only displays 30 pictures in it's code at the same time, that's the reason why I was only getting 30 links (and in InsaPy, the like by user feature also only do 30 likes).
I fixed it by getting links every time you move the page down, to get all of them line by line.

**Comment by justdvl** [comment]
Everything is working flawlessly, 
I managed to do a Pull Request
It si my first time ever so hope I did all correctly 0-)

**Comment by deniskrafczyk** [comment]
@justdvl thank you so much! you are kind of a hero i think ;)

**Comment by guifelix** [comment]
@justdvl since you managed to fix it, did you do a pull request just in this project or in instapy as well?
btw, tnx for the fix!

**Comment by justdvl** [comment]
They already fixed it in Instapy, just pull requests take longer to get through as they want to make sure all is fine. Just be patient.
But honestly, this fix is super simple and I don't see what can go wrong there. 
Meanwhile I also figured out even shorter way to write it..
