### ISSUE TITLE
Read user's bio?

### ISSUE THREAD

**Issue by daniel-ed** [timgrossmann/instagram-profilecrawl#35]
Is there a way to extract a user's bio text and write it into a file?

**Comment by daniel-ed** [comment]
No way?

**Comment by justdvl** [comment]
I can do it.

**Comment by justdvl** [comment]
I added this feature, , it's about adding:

`try:
    bio = container.find_element_by_class_name('_tb97a')\
                        .find_element_by_tag_name('span').text                      
  except:
    print ("\nBio is empty")
    bio = ""`

into the get_user_info method.

I will wait for Tim to approve it.

**Comment by timmoh** [comment]
@timgrossmann can be closed
