### ISSUE TITLE
IndexError: list index out of range - Video post

### ISSUE THREAD

**Issue by laurent-d** [timgrossmann/instagram-profilecrawl#4]
Hi @timgrossmann 

Thanks for your amazing work !!!
For some obvious reason your app stop to work since there are videos posts ..
The error is     img = imgs[1].get_attribute('src')
IndexError: list index out of range

Do you have an idea about this issue ?
Regards

Laurent

**Comment by timgrossmann** [comment]
@laurent-d Hmm... well it works when crawling my own profile which also has videos.
Could you give me an username for which this error will occur?

**Comment by laurent-d** [comment]
Thanks @timgrossmann !
I tried with your profile.
I use the last version of Selenium 3.33 for Mac.
Please see below

MacBook-Pro-de-Laurent:instagram-profilecrawl laurentdelacerda$ python3.5 crawl_profile.py grossertim
Extracting information from grossertim
- Could not get information from post: https://www.instagram.com/p/BSHUbpSF61n/?taken-by=grossertim
Traceback (most recent call last):
  File "crawl_profile.py", line 20, in <module>
    information = extract_information(browser, username)
  File "/Users/laurentdelacerda/instagram-profilecrawl/util/extractor.py", line 117, in extract_information
    img, tags, likes, comments = extract_post_info(browser)
  File "/Users/laurentdelacerda/instagram-profilecrawl/util/extractor.py", line 34, in extract_post_info
    img = imgs[1].get_attribute('src')
IndexError: list index out of range
MacBook-Pro-de-Laurent:instagram-profilecrawl laurentdelacerda$ 

It stop when it arrive to video

**Comment by clbailey** [comment]
I'm getting the same error. @timgrossmann, which versions are you using for Python and Selenium? 

I tried with Python 3.6.1 and Selenium 3.3.3. I'm not familiar with Python or Selenium, but I can try other tests if you have suggestions.

**Comment by nacimgoura** [comment]
Hi @clbailey ,
I was inspired by this project to make my own script in Javascript. If you know a little nodeJS and npm, you can test my program. There are still bugs but I fix them quickly.

**Comment by timgrossmann** [comment]
@laurent-d @clbailey This is really weird, there is no problem with videos for me... I actually covered that case in my script...

For the version information... 
selenium (2.53.6)

Make sure to run it with:

```bash
python3.5 ...
```

**Comment by laurent-d** [comment]
I tried without success same.. thanks for your support

**Comment by timgrossmann** [comment]
@laurent-d I'm really sorry you get that problems...
I will look into the code and try to fix it.

**Comment by laurent-d** [comment]
Hi @timgrossmann, @nacimgoura found a similar issue on his nodejs script (https://github.com/nacimgoura/instagram-profilecrawl) .
The language of the browser change the instagram display.
Hope it's the same issue and it helps you.

**Comment by timgrossmann** [comment]
@laurent-d Thank you, yes that's the problem. Thank you for pointing it out.

**Comment by timgrossmann** [comment]
@laurent-d Please pull the newest version and try again.

**Comment by khaeransori** [comment]
I still get this errror even when I already pull the newest version

**Comment by timgrossmann** [comment]
@khaeransori 

```
Update crawl_profile.py
timgrossmann committed on GitHub 3 days ago
```

**Comment by khaeransori** [comment]
@timgrossmann I'm sorry i miss that commits, but I still getting this error
on particular account
Can you check this instagram account @mamiomamacha ?
