### ISSUE TITLE
Scrolling Profile no stop

### ISSUE THREAD

**Issue by gustafsom** [timgrossmann/instagram-profilecrawl#42]
Good morning people.

I started using Instagram-profilecrawl. But a problem.

It is not to load all the posts.

The message at the prompt is:

```
...
Scrolling profile 324/380
Scrolling profile 336/380
Scrolling profile 348/380
Scrolling profile 360/380
Scrolling profile 372/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
Scrolling profile 379/380
```

I already tried to increase `sleep `in `extractor.py` but no work

**Comment by justdvl** [comment]
So it means instagram is telling the profile has 380 photos but script only found 379.
Weird.
What is the profile if I can ask?
I can fix it tonight, it is easy fix.

**Comment by gustafsom** [comment]
This happens on some accounts.

One of these accounts is: gelateria_roma

**Comment by justdvl** [comment]
Hello, I made a fix, you can already change the extractor.py file in your local copy and it will work.

**Comment by gustafsom** [comment]
worked perfectly. Thank you.
