### ISSUE TITLE
[Feature Request] - help needed: crawl only the N most recent posts

### ISSUE THREAD

**Issue by noamb3** [timgrossmann/instagram-profilecrawl#44]
Hello,
I need your assistance.
How can I download the most N recent posts ? (it takes a lot of time to process the entire profile posts in case there are many posts)

Thanks.
Noam

**Comment by justdvl** [comment]
Hi, I have included this option in the new pull request.
Before it is pulled you can download my fork.

Default value is to scroll only first 12000 posts now.
You can change it by changing limit_amount variable in crawl_profile.py
That limit will auto-change to be multiplication of 12, so if you would set the variable to be for example 20, it will be rounded up to be 24.

**Comment by noamb3** [comment]
Thanks a lot. It works well.
Why there is a limit of 12 ?
Actually, I need only the recent published post

**Comment by justdvl** [comment]
Well, it's a technical reason, when Instagram loads a profile, it loads 12 images.. and then when you scroll, 12 more.. I thought that is not so important, but it is possible to get rid of this graduality and be able to only get first n posts. Do you want me to do it?

**Comment by sionking** [comment]
I also want onlt last post please.

**Comment by sionking** [comment]
and number of posts is not true when you grab only last 12 it will say 12, instead of 245 ... real posts number.
