### ISSUE TITLE
Terminate

### ISSUE THREAD

**Issue by s1011448** [timgrossmann/instagram-profilecrawl#47]
I'm encountering 
"bio:
Error: Couldn't get user profile.
Terminating" 
How can I solve this?
I will be grateful for any help you can provide.

**Comment by justdvl** [comment]
It works for me..
Go to file extractor.py and to line 114 and change

`  except:
    print ("\nError: Couldn't get user profile.\nTerminating")`

`  except Exception as e:
    print (e)
    print ("\nError: Couldn't get user profile.\nTerminating")`

Then write here the error message.

**Comment by justdvl** [comment]
So you know where lies the problem. Someone will maybe be able to help you.
It is something about your configuration, where I am not expert on. I can
only ask, do you have file unicodes.md in your assets directory?
Solution 2 could be: delete lines 18,19,20,21 from extractor.py

**Comment by s1011448** [comment]
Thanks a lot~
