### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by kleahey** [timgrossmann/instagram-profilecrawl#53]
Getting the following error after scrolling the profile and scrapping the first link:

`Traceback (most recent call last):
  File "crawl_profile.py", line 33, in <module>
    information, user_commented_list = extract_information(browser, username, limit_amount)
  File "/Users/kevinleahey/Git/instagram-profilecrawl/util/extractor.py", line 225, in extract_information
    caption, location_url, location_name, location_id, lat, lng, img, tags, likes, comments, date, user_commented_list = extract_post_info(browser)
TypeError: 'NoneType' object is not iterable`

I looked at the extract_post_info method, but nothing stuck out to me. Any thoughts?

**Comment by kleahey** [comment]
Seems like this is related to lines 127-141 of extractor.py.

If there are no comments on the post `tags = comments[0].text` is causing script to fail.

I updated the `else` statement to `elif len(comments) == 1:` and that allowed the script to run fully. I'm not sure if that would have broken anything...

**Comment by juliavollmer** [comment]
I had the same issue, but it is working now fine after I unindented line 140 and 141.

**Comment by ZeusFSX** [comment]
I found why it is problem generate. If the post doesn`t have comments even from authors, I will get 
'''TypeError: 'NoneType' object is not iterable'''

**Comment by wecanfuture** [comment]
@juliavollmer can you please post your code?

**Comment by davasu** [comment]
Hi, i had the same issue and tried to fix but nothing works, someone can help?. I thinks is something wrong when the script try to "return" on line 142:

Line 142: return caption, location_url, location_name, location_id, lat, lng, img, tags, int(likes), int(len(comments) - 1), date, user_commented_list

Error:

Traceback (most recent call last):
  File "crawl_profile.py", line 33, in <module>
    information, user_commented_list = extract_information(browser, username, limit_amount)
  File "/home/administrador/instagram-profilecrawl/util/extractor.py", line 226, in extract_information
    caption, location_url, location_name, location_id, lat, lng, img, tags, likes, comments, date, user_commented_list = extract_post_info(browser)
TypeError: 'NoneType' object is not iterable

**Comment by justdvl** [comment]
Can you please give me example of username where this problem is happening?

**Comment by davasu** [comment]
Hi @justdvl, the problem occurs with this user https://www.instagram.com/whereistravel/ in the last post, i think is something wrong when try to get the statistics from each post and with this user betwen post 8 and 11 https://www.instagram.com/cristian.traveler.24/

**Comment by justdvl** [comment]
Looks like @alanwuha wrote this part of the code, maybe he will fix it soon :) If now I can look at it.

**Comment by davasu** [comment]
Thanks a lot @justdvl i will wait for any update from @alanwuha 👍

**Comment by justdvl** [comment]
No response, so I have done the fix ;)

https://github.com/timgrossmann/instagram-profilecrawl/pull/58
