### ISSUE TITLE
Broken after Instagram updated profiles.

### ISSUE THREAD

**Issue by andrewjburnett** [timgrossmann/instagram-profilecrawl#54]
The error message is suppressed so I can't post the error beyond: 

$python crawl_profile.py john
Waiting 10 sec
Extracting information from john

Error: Couldn't get user profile.
Terminating

**Comment by justdvl** [comment]
The problem is, the Chrome window doesn't even open, program doesn't even run anymore (for me)

**Comment by justdvl** [comment]
I have done the fix 
https://github.com/timgrossmann/instagram-profilecrawl/pull/55

**Comment by timgrossmann** [comment]
@andrewjburnett Please retry with the fix of @justdvl and close the issue if everything is working again.

**Comment by timmoh** [comment]
works fine since a month
