### ISSUE TITLE
Empty Caption

### ISSUE THREAD

**Issue by arashsyh** [timgrossmann/instagram-profilecrawl#57]
Hello.
Line 50 to 57 in extractor.py file is where, post's caption will have read.
but it seems in new version of instagram HTML file it doesn't work properly,
i fixed this issue, just replace all of codes in try block with this line:
`caption = post.find_element_by_class_name('gElp9').find_element_by_tag_name('span').text`
Be lucky :-)

**Comment by justdvl** [comment]
Hi, what you suggest didnt work for me. 
Main tricky problem was with spacing of return statement, it was included in the if condition. 
I am doing PR now.

**Comment by timmoh** [comment]
does it work now? can we close the issue?

**Comment by arashsyh** [comment]
@timmoh 
Of course, thanks for your Patient
