### ISSUE TITLE
absolute import instead of a relative one?

### ISSUE THREAD

**Issue by wecanfuture** [timgrossmann/instagram-profilecrawl#59]
File "crawl_profile.py", line 5, in <module>
    from .settings import Settings
SystemError: Parent module '' not loaded, cannot perform relative import

I was running into this issue i [googled a bit and found ](https://stackoverflow.com/questions/33837717/systemerror-parent-module-not-loaded-cannot-perform-relative-import)

so i changed line 5 to: 

> #!/usr/bin/env python3.5
>"""Goes through all usernames and collects their information"""
>import json
>from util.settings import Settings

works for me

**Comment by timmoh** [comment]
fixed in #63 
can be closed
