### ISSUE TITLE
Comments not exceeding 25?

### ISSUE THREAD

**Issue by nishanthkorupolu** [timgrossmann/instagram-profilecrawl#60]
The number of comments are stuck at 25 for me
Like so:
"likes": 1029020,
"comments": 25

Can anyone help me to fix this?

**Comment by davasu** [comment]
Same problem here!

**Comment by nishanthkorupolu** [comment]
I fixed that error by changing 'load more comments' to 'Load more comments', changing comments[1].find_element_by_tag_name('button').click() to comments[1].find_element_by_tag_name('a').send_keys("\n")

**Comment by timmoh** [comment]
see here: #65 
can be closed
