### ISSUE TITLE
Couldn't get user profile.

### ISSUE THREAD

**Issue by wecanfuture** [timgrossmann/instagram-profilecrawl#61]
Hello, 

now i am running into straight errors. 

When i execute this script i get the return:

Couldn't get user profile.

Anyone any idea?

**Comment by timmoh** [comment]
did you check if the user file exists in insta? please post config

**Comment by Psycoguana** [comment]
I get the same thing using my own profile

**Comment by timmoh** [comment]
works as designed.
what information should be scraped if the user has a private profile
