### ISSUE TITLE
bug report . 

### ISSUE THREAD

**Issue by 404Fel** [timgrossmann/instagram-profilecrawl#7]
i got this error i must be the most annoying user of your scrpit but i can't figure what i did wrong
 
Traceback (most recent call last):
  File "crawl_profile.py", line 27, in <module>
    information = extract_information(browser, username)
  File "/Users/Desktop/instagram-profilecrawl/util/extractor.py", line 117, in extract_information
    img, tags, likes, comments = extract_post_info(browser)
  File "/Users/Desktop/instagram-profilecrawl/util/extractor.py", line 34, in extract_post_info
    img = imgs[1].get_attribute('src')
IndexError: list index out of range
thanks for the support

**Comment by ToJen** [comment]
Funny, I was debugging that yesterday. On line 31, he called 
`post = browser.find_element_by_class_name('_tjnr4')` but I can't find that class. Wondering if it has been changed to something else.

**Comment by newbie-dev7** [comment]
have the same issue and i'm not familiar with code at all .

**Comment by timgrossmann** [comment]
@404Fel @ToJen @newbie-dev7 That's interesting, the element still exists when I check it out...
Must be a locational thing...

**Comment by timgrossmann** [comment]
Found the problem... It does not work with videos anymore.

Would be perfect if you could post the image or link to the post on which the script crashed next time 😉 

I'll fix it

**Comment by timgrossmann** [comment]
Should be fixed by [This commit](https://github.com/timgrossmann/instagram-profilecrawl/commit/f7812f9fc8191ede0c823b9f5d413fd6d2651af3)

Just `pull` and try again 😉

**Comment by newbie-dev7** [comment]
thanks @timgrossmann but there is the new error message 
 

- Could not get information from post: https://www.instagram.com/p/BTOf3S4AR0j/?taken-by=felix.bw
Traceback (most recent call last):
  File "crawl_profile.py", line 29, in <module>
    with open('./profiles/' + username + '.json', 'w') as fp:
IOError: [Errno 2] No such file or directory: './profiles/404hello.json'

should i just make a depository profiles/404hello.json in the profilcraw ?

**Comment by timgrossmann** [comment]
Yes...
I'm sorry, this got lost on the last push...
I'll re-add that

**Comment by newbie-dev7** [comment]
@timgrossmann its actually work without any error but the file .json that been created only contain informations about my post nowhere to find my follower list /people i do follow in the .json

**Comment by timgrossmann** [comment]
@newbie-dev7 That feature actually isn't present at all 😉
