### ISSUE TITLE
TypeError on save_profile_json() 

### ISSUE THREAD

**Issue by samu91gn** [timgrossmann/instagram-profilecrawl#72]
Traceback (most recent call last):
  File "crawl_profile.py", line 33, in <module>
    Datasaver.save_profile_json(username,information)
TypeError: unbound method save_profile_json() must be called with Datasaver inst
ance as first argument (got str instance instead)

I didn't do any change to the code so far.

**Comment by timmoh** [comment]
how did you start the crawl_profile.py ?

**Comment by samu91gn** [comment]
Hi, thanks for your reply, I fixed the error above by using python 3.5 as suggested (I was trying with 2.7 before).
Nevertheless I was experiencing an **OSError: [Errno 22] Invalid argument on datasaver.py, line 16, in save_profile_json with open(file_profile, 'w')**
the problem has to do with the file name containing colons: "%Y-%m-%d %H:%M:%S", not allowed in a file name in Windows.
I also replaced the forward slashes (/) with double backslashes (\\)

**Comment by timmoh** [comment]
Hi I just commit #74 it should work on windows now as well.
If it works please close issue

**Comment by samu91gn** [comment]
it works now :)
