### ISSUE TITLE
We can't use pyvirtualdisplay on Windows

### ISSUE THREAD

**Issue by edotfar** [timgrossmann/instagram-profilecrawl#76]
Hi, 
In windows we have a problem with Display function (from pyvirtualdisplay import Display)
actually we can't use pyvirtualdisplay on Windows.
It is just a wrapper that calls Xvfb. Xvfb is a headless display server for the X Window System. Windows does not use the X Window System.

How can I use this in windows OS ?

**Comment by timmoh** [comment]
there is no official support for windows. try macos, raspberry or any other unix based os
