### ISSUE TITLE
Instagram Update - Class Name Issue 

### ISSUE THREAD

**Issue by starbuck614** [timgrossmann/instagram-profilecrawl#78]
Hello, 

I keep getting an error when I run extractor.py particularly in line 14. I think Instagram updated their class name because this is the error I get after changing the error code in line 301-304.  I'm not sure how to find the correct class name. All help is greatly appreciated!

>`Message: no such element: Unable to locate element: {"method":"class name","selector":"v9tJq"}'

Error Code I put in:

`except Exception as e:
print(e)
print ("\nError: Couldn't get user profile.\nTerminating")
quit()`

**Comment by timmoh** [comment]
tested it with several profile. everything works

**Comment by singelnspuis** [comment]
Hello I am getting a similar error message:
`Message: no such element: Unable to locate element: {"method":"class name","selector":"Xl2Pu"}'

on all the profiles I try to crawl. At the end of the crawl I am able to view the number of posts, followers, following, etc but no posts.

Thank you.

**Comment by dshahrokhian** [comment]
Same here!
