### ISSUE TITLE
Settings Error Message

### ISSUE THREAD

**Issue by daniel-ed** [timgrossmann/instagram-profilecrawl#84]
After installation I get the following error:

```
from util.settings import Settings
ImportError: No module named settings
```

**Comment by timmoh** [comment]
please post settings.py & your start skript

**Comment by daniel-ed** [comment]
settings.py:

`import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

class Settings:
    profile_location = os.path.join(BASE_DIR, 'profiles')
    profile_commentors_location = os.path.join(BASE_DIR, 'profiles')
    profile_file_with_timestamp = True
    profile_commentors_file_with_timestamp = True
    limit_amount = 12000
    scrap_posts_infos = True
    output_comments = False
    sleep_time_between_post_scroll = 1.5
    mentions = True`

Start Script:

`import json
import os.path
import logging
import argparse
try:
    from instagram_private_api import (
        Client, __version__ as client_version)
except ImportError:
    import sys
    sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
    from instagram_private_api import (
        Client, __version__ as client_version)


if __name__ == '__main__':

    logging.basicConfig()
    logger = logging.getLogger('instagram_private_api')
    logger.setLevel(logging.WARNING)

    # Example command:
    # python examples/savesettings_logincallback.py -u "yyy" -p "zzz" -settings "test_credentials.json"
    parser = argparse.ArgumentParser(description='Pagination demo')
    parser.add_argument('-u', '--username', dest='username', type=str, required=True)
    parser.add_argument('-p', '--password', dest='password', type=str, required=True)
    parser.add_argument('-debug', '--debug', action='store_true')

    args = parser.parse_args()
    if args.debug:
        logger.setLevel(logging.DEBUG)

    print('Client version: %s' % client_version)
    api = Client(args.username, args.password)

    # user_id = '2958144170'
    origin = api.username_info('edelfilm')
    user_id = origin['user']['pk']
    followers = []
    print(api.user_info(user_id))
    results = api.user_followers(user_id, rank_token)

    followers.extend(results.get('users', []))

    next_max_id = results.get('next_max_id')
    while next_max_id:
        try:
            print(api.user_info(next_max_id))
        except Exception as e:
            print(e)
            pass
        results = api.user_followers(user_id, rank_token=uuid, max_id=next_max_id)
        followers.extend(results.get('users', []))
        if len(followers) >= 500:       # get only first 600 or so
            break
        next_max_id = results.get('next_max_id')

    followers.sort(key=lambda x: x['pk'])
    # print list of user IDs
    print(json.dumps([u['username'] for u in followers], indent=2))
    # for u in followers`

**Comment by timmoh** [comment]
???
i think your are in the wrong repo:
look here => https://github.com/ping/instagram_private_api
or use this repo and have a look at the crawl_profile.py
