### ISSUE TITLE
import data in R w/ jsonlite dosent work..

### ISSUE THREAD

**Issue by phermann1988** [timgrossmann/instagram-profilecrawl#85]
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
          ppy", "#goodtime", "#funny", ...],        "likes": 284,     
                     (right here) ------^

i used the given example in the READ.ME but all my scraped json files dosent work w/ jsonlite

**Comment by timmoh** [comment]
have you checked the json files with other tools? Perhaps R/jsonlite has a problem. Perhaps also some encoding problems?

**Comment by phermann1988** [comment]
yes, the problem is the output json isn't valid (checked w/ https://jsonlint.com/; https://jsonformatter.curiousconcept.com/)..

**Comment by timmoh** [comment]
@phermann1988 could you pls update und check if there is still an error.
if yes: please post the json file with error
