### ISSUE TITLE
error in functionality

### ISSUE THREAD

**Issue by rushabhsooni** [timgrossmann/instagram-profilecrawl#86]
as the structure is changed by Instagram, can we divide the extractor page more specific as XPath can solve the problem. I have progressed in bio , but unable to solve the comments section.

**Comment by timmoh** [comment]
pls give some more details...
perhaps the commit yesterday solves your problem

**Comment by rushabhsooni** [comment]
ya thanks, yesterday's commit did solve the issue of bio, 
But it does get any comments, does retrieving comments function open's another page?
so I can do it manually.

**Comment by timmoh** [comment]
pls check new commit @rushabhsooni
