### ISSUE TITLE
cron log_stats.py with dynamic title .json

### ISSUE THREAD

**Issue by ThomasViennet** [timgrossmann/instagram-profilecrawl#95]
Hi,

Thanks for your code, its very usefull !
I would like use a cron to run log_stats.py username but the title of the .json is dynamic like this usernam_2018-09-11 00-19-40.json

Can you help me to automise this please ?

**Comment by timmoh** [comment]
@ThomasViennet should work now. pls update
you also could use `python3 log_stats.py` for importing all json user files

**Comment by ThomasViennet** [comment]
Thanks !
