### ISSUE TITLE
Can not get comments

### ISSUE THREAD

**Issue by oguzhankarabulut** [timgrossmann/instagram-profilecrawl#97]
Firstly thanks for sharing, it is amazing. I installed and tried i can get all datas as you said but i can not get comments. I can get comments count but comments list is empty like that:

>             },
            "img": "https://scontent-sof1-1.cdninstagram.com/vp/fd31a0e9fb669a4a6a427234a7aa5f2f/5C360E0A/t51.2885-15/e35/17334216_1505196182846160_5268358866986336256_n.jpg",
            "preview_img": "https://scontent-sof1-1.cdninstagram.com/vp/c70d938b078e49bd75cc0ea7cd1de4d1/5C1C6070/t51.2885-15/sh0.08/e35/s640x640/16465363_1481966425161017_1860983477948645376_n.jpg",
            "date": "2017-03-14T19:24:47.000Z",
            "tags": [
                "#tb"
            ],
            "likes": 13560,
            "url": "https://www.instagram.com/p/BQgJb5hjQM1/?taken-by=alperrende",
            "comments": {
                "count": 57,
                "list": []
            },
            "mentions": []
        },
        {
            "caption": "\"Dal\u0131p gidenleri kendine getirme gen\u00e7lik d\u00fcstrib\u00fct\u00f6rl\u00fc\u011f\u00fc\" ba\u015fvurumu yapt\u0131m, raad olun! #kendinegel @nescafe3u1arada",
            "location": {
                "location_url": "",
                "location_name": "",
                "location_id": 0,
                "latitude": "",
                "longitude": ""
            },
            "img": "https://scontent-sof1-1.cdninstagram.com/vp/fcb363e981bf007b3df98497fa1d5ee9/5B9B7925/t51.2885-15/e15/22159189_153027205291011_4283330571737759744_n.jpg",
            "preview_img": "https://scontent-sof1-1.cdninstagram.com/vp/c70d938b078e49bd75cc0ea7cd1de4d1/5C1C6070/t51.2885-15/sh0.08/e35/s640x640/16465363_1481966425161017_1860983477948645376_n.jpg",
            "date": "2017-10-06T17:02:17.000Z",
            "tags": [
                "#kendinegel"
            ],
            "likes": 130314,
            "url": "https://www.instagram.com/p/BQgJb5hjQM1/?taken-by=alperrende",
            "comments": {
                "count": 428,
                "list": []
            },
            "mentions": []
        },

this is a part of my json file. How can i solve that problem. 
Regards

**Comment by timmoh** [comment]
just updated the documentation, have a look at it.
i think you just have to add `Settings.output_comments = True`

**Comment by oguzhankarabulut** [comment]
Thanks! You may close the topic :)

**Comment by oguzhankarabulut** [comment]
i can do too :D
